**PANDAS LIBRARY**

In [ ]:
###<<<<<<<<<<<<<<<<<   PANDAS      >>>>>>>>>>>>>>>>>>###
# PIP install pandas
import pandas as pd

**Data frame create using dictionary**

In [ ]:
data = {"Name":['Rishi','Harshit','kartik','yash'],
       "Subject":['physics','chemistry' , 'physics','computer science'],
       "college":['poornima','biet','lord','jecrc']}
data

{'Name': ['Rishi', 'Harshit', 'kartik', 'yash'],
 'Subject': ['physics', 'chemistry', 'physics', 'computer science'],
 'college': ['poornima', 'biet', 'lord', 'jecrc']}

**A dataframe is a data structure constructed with rows and columns, similar to a database or Excel spreadsheet. It consists of a dictionary of lists in which the list each have their own identifiers or keys, such as “last name” or “food group.”**

In [ ]:
df = pd.DataFrame(data)
df

      Name           Subject   college
0    Rishi           physics  poornima
1  Harshit         chemistry      biet
2   kartik           physics      lord
3     yash  computer science     jecrc

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df["name"]

0      rishi
1    harshit
2     kartik
3       yash
Name: name, dtype: object

In [ ]:
type(df["name"])

pandas.core.series.Series

**notepad file of bikes brand ownsersgip price age soon**

In [ ]:
df = pd.read_csv("/content/Used_Bikes (4).csv")
df.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [ ]:
type(df)

pandas.core.frame.DataFrame

***we want to take information from list***

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  object
 1   price       32648 non-null  float64
 2   city        32648 non-null  object
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  object
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  object
dtypes: float64(4), object(4)
memory usage: 2.0+ MB

**columns and rows information**

In [ ]:
df.shape

(32648, 8)

***DatA TYPES IN data frame***

In [ ]:
df.dtypes

bike_name      object
price         float64
city           object
kms_driven    float64
owner          object
age           float64
power         float64
brand          object
dtype: object

**for top five records**

In [ ]:
df.head(10)                    #top first five
df.head()                     #first five

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

***for last five records***

In [ ]:
df.tail()

,bike_name,price,city,kms_driven,owner,age,power,brand
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

***data types in series***

In [ ]:
df['city']
df.tail()

,bike_name,price,city,kms_driven,owner,age,power,brand
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [ ]:
df[['brand','age','price']]
df.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [ ]:
df[['bike_name','price']]
df.tail()

,bike_name,price,city,kms_driven,owner,age,power,brand
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

**LOC AND ILOC**

In [ ]:
df.loc[0:100]                  #here it gives 101 rows  it print till ending point

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
96,Suzuki Gixxer Fi 150cc ABS,96700.0,Vadodara,5100.0,First Owner,1.0,150.0,Suzuki
97,Hero Splendor plus 100cc,31900.0,Delhi,9000.0,First Owner,5.0,100.0,Hero
98,Bajaj Pulsar 150cc,35000.0,Visakhapatnam,44480.0,First Owner,13.0,150.0,Bajaj
99,KTM Duke 390cc,240000.0,Bangalore,11000.0,First Owner,3.0,390.0,KTM
100,Honda CBR 250R,68000.0,Delhi,16000.0,First Owner,7.0,250.0,Honda

In [ ]:
df.iloc[0:100]                     #here it gives 100 rows        it print till (ending poiunt - 1) point

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
95,Bajaj Pulsar 150cc,60000.0,Pune,2000.0,First Owner,2.0,150.0,Bajaj
96,Suzuki Gixxer Fi 150cc ABS,96700.0,Vadodara,5100.0,First Owner,1.0,150.0,Suzuki
97,Hero Splendor plus 100cc,31900.0,Delhi,9000.0,First Owner,5.0,100.0,Hero
98,Bajaj Pulsar 150cc,35000.0,Visakhapatnam,44480.0,First Owner,13.0,150.0,Bajaj
99,KTM Duke 390cc,240000.0,Bangalore,11000.0,First Owner,3.0,390.0,KTM

In [ ]:
df.loc[0:100,['bike_name','age','price']]          #it is not acc.to indexing value
df.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [ ]:
df.iloc[0:32000,0:4]                               # it is acc. to indexing value
df.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [ ]:
df.iloc[500:800,0:4]
# df.loc[600:1200,['brand','owner','city','price']]

                                    bike_name     price     city  kms_driven
500                Harley-Davidson Street 750  371100.0     Pune      6300.0
501                       Bajaj Discover 100M   30000.0    Thane      7334.0
502                  Bajaj Avenger Street 150   70000.0  Kolkata      3400.0
503               Royal Enfield Classic 350cc  131000.0    Delhi      9900.0
504                        Bajaj Pulsar NS160   65000.0    Delhi      7000.0
..                                        ...       ...      ...         ...
795                   Yamaha YZF-R15 V3 150cc  110900.0    Delhi      4200.0
796               Royal Enfield Classic 350cc  135000.0    Delhi      9000.0
797  Honda CB Hornet 160R Special Edition STD   72500.0  Chennai      9500.0
798             Bajaj Platina  Alloy ES-100cc   33000.0    Delhi     14000.0
799                        Bajaj Pulsar RS200   94300.0    Delhi     13000.0

[300 rows x 4 columns]

**filtering with condition in data types**

In [ ]:
df[df['price']<=5000]
df[df['price']<=60000]

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
5,Yamaha FZs 150cc,53499.0,Delhi,25000.0,First Owner,6.0,150.0,Yamaha
7,Hero Splendor Plus Self Alloy 100cc,45000.0,Delhi,12645.0,First Owner,3.0,100.0,Hero
13,Bajaj Discover 100M,29499.0,Delhi,20000.0,First Owner,8.0,100.0,Bajaj
14,Bajaj Discover 125M,29900.0,Delhi,20000.0,First Owner,7.0,125.0,Bajaj
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [ ]:
df[df['age']<=2]
df.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [ ]:
df["brand"].value_counts()
df[df['brand']=='Royal Enfield']

,bike_name,price,city,kms_driven,owner,age,power,brand
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield
23,Royal Enfield Classic Chrome 500cc,121700.0,Kalyan,24520.0,First Owner,5.0,500.0,Royal Enfield
36,Royal Enfield Classic 350cc,98800.0,Kochi,39000.0,First Owner,5.0,350.0,Royal Enfield
...,...,...,...,...,...,...,...,...
32601,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield
32614,Royal Enfield Bullet Electra 350cc,105000.0,Delhi,20000.0,First Owner,4.0,350.0,Royal Enfield
32633,Royal Enfield Classic 350cc,87000.0,Gautam Buddha Nagar,16336.0,First Owner,7.0,350.0,Royal Enfield
32634,Royal Enfield Thunderbird 350cc,70000.0,Mumbai,13858.0,Second Owner,11.0,350.0,Royal Enfield
32639,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield

all brand names vechiles are counted in a row

In [ ]:
df["brand"].value_counts()

brand
Bajaj              11213
Hero                6368
Royal Enfield       4178
Yamaha              3916
Honda               2108
Suzuki              1464
TVS                 1247
KTM                 1077
Harley-Davidson      737
Kawasaki              79
Hyosung               64
Benelli               56
Mahindra              55
Triumph               26
Ducati                22
BMW                   16
Jawa                  10
MV                     4
Indian                 3
Ideal                  2
Rajdoot                1
LML                    1
Yezdi                  1
Name: count, dtype: int64

***all city names vechiles are counted in a row***

In [ ]:
df["city"].value_counts()

city
Delhi            7318
Bangalore        2723
Mumbai           2591
Hyderabad        2160
Pune             1724
                 ...
Surendranagar       1
Khandela            1
Mohammadabad        1
Shimla              1
Sidhi               1
Name: count, Length: 443, dtype: int64

***only city names not including their properties***

In [ ]:
df["city"].value_counts().keys()

Index(['Delhi', 'Bangalore', 'Mumbai', 'Hyderabad', 'Pune', 'Chennai',
       'Lucknow', 'Jaipur', 'Ghaziabad', 'Ahmedabad',
       ...
       'Raigarh', 'Chikkaballapur', 'Kasba', 'Marandahalli', 'Badaun',
       'Surendranagar', 'Khandela', 'Mohammadabad', 'Shimla', 'Sidhi'],
      dtype='object', name='city', length=443)

In [ ]:
df["city"].value_counts().values

array([7318, 2723, 2591, 2160, 1724, 1619, 1294, 1007,  938,  905,  776,
        651,  649,  640,  635,  625,  621,  621,  617,  611,  609,  608,
        608,  100,   97,   94,   87,   75,   57,   52,   46,   36,   33,
         30,   29,   27,   27,   25,   23,   23,   22,   21,   19,   18,
         17,   16,   15,   14,   13,   13,   13,   12,   12,   12,   12,
         12,   11,   11,   11,   11,   10,   10,   10,   10,   10,    9,
          9,    9,    9,    8,    8,    8,    8,    8,    8,    7,    7,
          7,    7,    7,    7,    7,    7,    7,    7,    6,    6,    6,
          6,    6,    6,    6,    5,    5,    5,    5,    5,    5,    5,
          5,    5,    5,    5,    5,    5,    5,    5,    5,    5,    4,
          4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
          4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
          4,    4,    4,    4,    4,    4,    4,    4,    3,    3,    3,
          3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
          3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
          3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
          3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
          3,    3,    2,    2,    2,    2,    2,    2,    2,    2,    2,
          2,    2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
          2,    2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
          2,    2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
          2,    2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
          2,    2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
          2,    2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
          2,    2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
          2,    2,    2,    2,    2,    2,    2,    2,    2,    2,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1])

***all places are wrtiteen in it. all are separately written***

In [ ]:
df["city"].unique()

array(['Ahmedabad', 'Delhi', 'Bangalore', 'Mumbai', 'Kalyan', 'Faridabad',
       'Mettur', 'Hyderabad', 'Kaithal', 'Gurgaon', 'Pune', 'Noida',
       'Nashik', 'Kochi', 'Allahabad', 'Samastipur', 'Nadiad', 'Lucknow',
       'Jaipur', 'Karnal', 'Gorakhpur', 'Vidisha', 'Hosur', 'Bagalkot',
       'Baripara', 'Agra', 'Dharwad', 'Vadodara', 'Jalandhar', 'Surat',
       'Chennai', 'Navi Mumbai', 'Gandhidham', 'Visakhapatnam',
       'Thrissur', 'Kolkata', 'Ernakulam', 'Barasat', 'Ghaziabad',
       'Bhubaneshwar', 'Amritsar', 'Bhopal', 'Hamirpur(hp)', 'Kottayam',
       'Arrah', 'Patiala', 'Ranga Reddy', 'Mandi', 'Ludhiana', 'Mandya',
       'Siliguri', 'Aurangabad', 'Kanpur', 'Bhilwara', 'Meerut', 'Rewari',
       'Ahmednagar', 'Wardha', 'Chandigarh', 'Ranchi', 'Panvel', 'Thane',
       'Jabalpur', 'Kota', 'Rohtak', 'Rajkot', 'Varanasi', '24 Pargana',
       'Banka', 'Nagpur', 'Banki', 'Pali', 'Chhatarpur', 'Katihar',
       'Mohali', 'Rudrapur', 'Coimbatore', 'Jajpur', 'Mysore', 'Adoni',
       'Bikaner', 'Malout', 'Jammu', 'Rajnandgaon', 'Unnao', 'Godhara',
       'Kolhapur', 'Satara', 'Siwan', 'Dadra & Nagar Haveli', 'Bhiwani',
       'Koppal', 'Nizamabad', 'Madurai', 'Ujjain', 'Palakkad',
       'Tiruvallur', 'Panchkula', 'Nanjangud', 'Jhansi', 'Sonipat',
       'Puttur', 'Hoshiarpur', 'Gohana', 'Gautam Buddha Nagar',
       'Durgapur', 'Palwal', 'Chatrapur', 'Howrah', 'Jind', 'Hubli',
       'Panipat', 'Bharatpur', 'Vellore', 'Ambala', 'Guwahati', 'Gangtok',
       'Rajahmundry', 'Tiruchirappalli', 'Belgaum', 'Balaghat', 'Jatani',
       'Asansol', 'Bilaspur', 'Thanjavur', 'Raigarh(mh)', 'Mandi Dabwali',
       'Basti', 'Bolpur', 'Aligarh', 'Balrampur', 'Ratnagiri', 'Muktsar',
       'Baran', 'Haldwani', 'Thiruvananthapuram', 'Indore', 'Buxar',
       'Chaksu', 'Haridwar', 'Bharuch', 'Muvattupuzha', 'Patna',
       'Simdega', 'Singhbhum', 'Bardhaman', 'Pathankot', 'Kharar',
       'Silchar', 'Jhalawar', 'Roorkee', 'Saharanpur', 'Solapur',
       'Gwalior', 'Alibag', 'Katni', 'Khedbrahma', 'Valsad', 'Satna',
       'Hooghly', 'Gurdaspur', 'Dadri', 'Amravati', 'Durg', 'Mehsana',
       'Lansdowne', 'Cuttack', 'Jaisalmer', 'Hanumangarh', 'Dungarpur',
       'Sri Ganganagar', 'Margao', 'Chinsurah', 'Bhatinda', 'Sibsagar',
       'Khalilabad', 'Dehradun', 'Anand', 'Sambalpur', 'Ankleshwar',
       'Purnia', 'Tiruverkadu', 'Bahadurgarh', 'Udaipur', 'Jodhpur',
       'Sheikhpura', 'Pondicherry', 'Sirsa', 'Godavari', 'Ajmer',
       'Moradabad', 'Raipur', 'Navsari', 'Herbertpur', 'Jamshedpur',
       'Ramanagar', 'Berhampur', 'Vijayawada', 'Murad Nagar',
       'Chandrapur', 'Jamtara', 'Uppidamangalam', 'Nalagarh', 'Una',
       'Chakan', 'Idukki', 'Shivpuri', 'Arkalgud', 'Bidar', 'Rupnagar',
       'Deoghar', 'Kanchipuram', 'Vapi', 'Medak', 'Kasargode', 'Dhanbad',
       'Dakshina Kannada', 'Ganaur', 'Jamalpur', 'Amraoti', 'Mangalore',
       'Deolali', 'Gandhinagar', 'Chitradurga', 'Chinchwad', 'Jhajjar',
       'Jagdalpur', 'Ranoli', 'Raiwala', 'Guntur', 'Badarpur', 'Adalaj',
       'Alipore', 'Bhawani Mandi', 'Mughalsarai', 'Kollam', 'Farukhabad',
       'Thiruvallur', 'Udaipurwati', 'Rasra', 'Latur', 'Krishna',
       'Gangaikondan', 'Warangal', 'Uluberia', 'Poonamallee', 'Nagaon',
       'Hissar', 'Kanyakumari', 'Morbi', 'Bankura', 'Virar', 'Tikamgarh',
       'Sultanpur', 'Tirunelveli', 'Bihar Shariff', 'Goa-panaji',
       'Ganganagar', 'Kolar', 'Bahadurpur', 'Batala', 'Budhlada',
       'Muzaffarnagar', 'Adyar', 'Calicut', 'Raigarh', 'Sonepat',
       'Chikkaballapur', 'Kasba', 'Bulandshahr', 'Burdwan', 'Anjar',
       'Marandahalli', 'Badaun', 'Namakkal', 'Puri', 'Alwar',
       'Surendranagar', 'Khandela', 'Kullu', 'Mohammadabad', 'Sangareddy',
       'Ghazipur', 'Shimla', 'Azamgarh', 'Chenani', 'Kanpur Nagar',
       'Trivandrum', 'Secunderabad', 'Kurukshetra', 'Dhariawad',
       'Bargarh', 'Gadarpur', 'Chikamaglur', 'Karim Nagar', 'Kotdwar',
       'Jalaun', 'Parola', 'Bareilly', 'Salem', 'Indi', 'Muzaffarpur',
       'Nayagarh', 'Jalgaon', 'Ambikapur', 'Udupi', 'Junagadh',
       'Dibrugarh', 'Faridkot', 'Naraingarh', 'Karwar',
       'Sant Kabir Nagar', 'Viramgam', 'Manali', 'Gadwal', 'Honavar',
       'Mathura', 'Khandwa', 'Solan', 'Sitapur', 'Betul', 'Anantapur',
       'Sholapur', 'Pinjore', 'Qadian', 'Sangrur', 'Jorhat', 'Palanpur',
       'Narnaul', 'Palamu', 'Falakata', 'Ferozepur', 'Porbandar',
       'Dwarka', 'Rangpo', 'Cannanore (kannur)', 'Churu', 'Baghpat',
       'Jhumri Tilaiya', 'Naihati', 'Virudhunagar', 'Dharmavaram',
       'Darbhanga', 'Nawanshahr', 'Sangli', 'Suri', 'Yamuna Nagar',
       'Vasai', 'Aluva', 'Sirsi', 'Bijapur', 'Krishnagar', 'Bhiwadi',
       'Bellary', 'Erode', 'Aquem', 'Nellore', 'Udhampur', 'Dhamtari',
       'Vandalur', 'Motihari', 'Dharwar', 'Shimoga', 'Jhunjhunu',
       'Bijnor', 'Yemmiganur', 'Bokaro', 'Kurnool', 'Srinagar', 'Ranip',
       'Davanagere', 'Rajouri', 'Begusarai', 'Goregaon', 'Bally',
       'Kachchh', 'Nagaur', 'Anekal', 'Mansa', 'Nanded', 'Dharamasala',
       'Chhindwara', 'Jamnagar', 'Zirakpur', 'Abohar', 'Barabanki',
       'Nabha', 'Kadapa', 'Perumbavoor', 'Sundargarh', 'Nazira',
       'Pratapgarh', 'Dharmapuri', 'Thangadh', 'Lonavala', 'Vizianagaram',
       'Kathua', 'Deesa', 'Tiruppur', 'Gadchiroli', 'Gangaghat', 'Bhuj',
       'Vastral', 'Phagwara', 'Kheda', 'Swaimadhopur', 'Kharagpur',
       'Jobner', 'Gondia', 'Bundi', 'Hamirpur', 'Dongargaon',
       'Mubarakpur', 'Tumkur', 'Sanand', 'Kartarpur', 'Bhavnagar',
       'Farrukhabad', 'Kadi', 'Seppa', 'Challakere', 'Dhubri', 'Deoria',
       'Akot', 'Alappuzha', 'Bhiwandi', 'Shillong', 'Osmanabad', 'Kendua',
       'Uran', 'Jaunpur', 'Hisar', 'Bodhan', 'Bhubaneswar', 'Raiganj',
       'Bhilai Nagar', 'Baloda', 'Anantnag', 'Berhampore', 'Silvasa',
       'Hospet', 'Palai', 'Sidhi'], dtype=object)

***total city are counted in this***

In [ ]:
df["city"].nunique()

443

In [ ]:
df["owner"].value_counts()

owner
First Owner             29964
Second Owner             2564
Third Owner               108
Fourth Owner Or More       12
Name: count, dtype: int64

***this all are the condition which can be used in the and operator***

In [ ]:
df[(df['price']<=85000) & (df['age']<=2) & (df['owner']=='First Owner')]

,bike_name,price,city,kms_driven,owner,age,power,brand
22,Hero Splendor iSmart Plus IBS 110cc,46500.0,Delhi,3500.0,First Owner,2.0,110.0,Hero
29,Honda X-Blade 160CC ABS,81200.0,Mettur,9100.0,First Owner,2.0,160.0,Honda
47,Mahindra Centuro NXT 110cc,28000.0,Jaipur,45000.0,First Owner,2.0,110.0,Mahindra
95,Bajaj Pulsar 150cc,60000.0,Pune,2000.0,First Owner,2.0,150.0,Bajaj
121,Hero Splendor iSmart Plus IBS 110cc,48672.0,Ernakulam,608.0,First Owner,2.0,110.0,Hero
...,...,...,...,...,...,...,...,...
8335,Bajaj Pulsar 150cc Neon,72000.0,Pune,3162.0,First Owner,2.0,150.0,Bajaj
8531,Hero Xtreme 200R ABS,85000.0,Bangalore,40.0,First Owner,2.0,200.0,Hero
8536,Hero Glamour i3s 125cc,75000.0,Gurgaon,7488.0,First Owner,2.0,125.0,Hero
8796,Hero Xtreme 200R ABS,85000.0,Bangalore,40.0,First Owner,2.0,200.0,Hero
9322,TVS Radeon 110cc Drum SBT,58000.0,Delhi,4020.0,First Owner,2.0,110.0,TVS

***data filter for self list***

In [ ]:
filter_df = df[(df['price']<=85000) & (df['age']<=5) & (df['owner']=='First Owner')]
filter_df.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
6,Honda CB Hornet 160R ABS DLX,85000.0,Delhi,8200.0,First Owner,3.0,160.0,Honda
7,Hero Splendor Plus Self Alloy 100cc,45000.0,Delhi,12645.0,First Owner,3.0,100.0,Hero

In [ ]:
filter_df [filter_df['city']=="Jaipur"]
df.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [ ]:
df[df['brand']=="Royal Enfield"]
df.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha